#FROM onap/ccsdk-ansible-server-image:${ccsdk.docker.version}
FROM onap/ccsdk-ansible-server-image:0.6.3

LABEL maintainer="SDN-C Team (sdnc@lists.openecomp.org)"

COPY Playbooks /opt/ansible-server/Playbooks
